### PR TITLE
Additional formats used in Pokémon XD Gale of Darkness (.DAT, .PKX, .GSW), slight cleanup and basic HAL DAT support

### PR DESCRIPTION
**Pull request by Neui**
Works without errors on my PAL Pokémon XD Gale of Darkness (GXXP01) copy.
I don't have other versions or related games, so testing is appreciated.

### CODE REVIEW

**Comment by Venomalia** [comment]
This looks very good I will test it soon with Pokémon Colosseum.

**Comment by Venomalia** [comment]
the PKX format in Colosseum is apparently not the same as in XD do you know something about this?

**Comment by Neui** [comment]
I also added support for the animated textures, since it turns out it is rather simple (the texture part).

> the PKX format in Colosseum is apparently not the same as in XD do you know something about this?

No because I don't have Colosseum to look into.

**Comment by Venomalia** [comment]
I didn't expect Pokemon XD to use so many different structures.
really good work!

**Pull request merged**
